### ISSUE TITLE
Failed to activate the rails-routes package

### ISSUE THREAD

**Issue by fabiantorresm** [aki77/atom-rails-routes#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.8.4
**OS**: linux 4.15.12-1-ARCH
**Thrown From**: [rails-routes](https://github.com/aki77/atom-rails-routes) package 0.1.5

### Stack Trace

Failed to activate the rails-routes package

```
At Unable to watch path

Error: Unable to watch path
    at HandleWatcher.start (/usr/lib/atom/node_modules/pathwatcher/lib/main.js:87:29)
    at new HandleWatcher (/usr/lib/atom/node_modules/pathwatcher/lib/main.js:20:12)
    at new PathWatcher (/usr/lib/atom/node_modules/pathwatcher/lib/main.js:140:30)
    at Object.exports.watch (/usr/lib/atom/node_modules/pathwatcher/lib/main.js:234:12)
    at Object.activate (/packages/rails-routes/lib/main.js:23:37)
    at Package.activateNow (/usr/lib/atom/src/package.js:225:27)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/lib/atom/src/package.js:896:75)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at PackageManager.triggerActivationHook (/usr/lib/atom/src/package-manager.js:721:34)
    at Workspace.handleGrammarUsed (/usr/lib/atom/src/workspace.js:1255:32)
    at TextEditor.observeGrammar (/usr/lib/atom/src/text-editor.js:728:5)
    at onDidAddPaneItem (/usr/lib/atom/src/workspace.js:499:16)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at PaneContainer.didAddPaneItem (/usr/lib/atom/src/pane-container.js:267:18)
    at Pane.addItem (/usr/lib/atom/src/pane.js:628:42)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:570:12)
    at Workspace.open (/usr/lib/atom/src/workspace.js:1028:12)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-vue 0.6.0 
ide-vue 0.1.8 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter-rails-best-practices 0.2.2 
nodejs-snippets 2.0.2 
rails-routes 0.1.5 
rails-snippets 2.18.0 
vuejs2-snippets 0.15.0 
```

**Comment by aki77** [comment]
Cleaning up stale PRs.
