### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reportBusyWhile' of null

### ISSUE THREAD

**Issue by marksack** [aki77/atom-rails-routes#3]
[Enter steps to reproduce:]

1. Open routes.rb file in atom

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Debian GNU/Linux
**Thrown From**: [rails-routes](https://github.com/aki77/atom-rails-routes) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'reportBusyWhile' of null

```
At /home/marksack/.atom/packages/rails-routes/lib/main.js:60

TypeError: Cannot read property 'reportBusyWhile' of null
    at Object.load (/packages/rails-routes/lib/main.js:60:28)
    at /packages/rails-routes/lib/main.js:22:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-updater-linux 1.2.2 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-erb 1.1.1 
linter-rails-best-practices 0.2.2 
linter-rubocop 2.2.3 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
pigments 0.40.2 
project-manager 3.3.6 
rails-i18n-autocomplete 0.4.0 
rails-routes 0.2.0 
rails-transporter 1.7.1 
seti-ui 1.10.0 
vim-mode-plus 1.32.0 
zentabs 0.8.9 
zentabs-fix 0.1.3 
```

**Comment by aki77** [comment]
Please try with the latest version.
